name:                shapes
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5


library:
  source-dirs: src

executables:
  shapes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - shapes

tests:
  shapes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - shapes
    - hspec
